### ISSUE TITLE
Custom Text

### ISSUE THREAD

**Issue by GauravCreed** [shlusiak/Freebloks-Android#14]
Hi @janisozaur 

How can i create my own name in intor screen? can u please guide me. i just follow the **intro.java** , but i can't get it.

Thanks. (_)

**Comment by janisozaur** [comment]
Huh? Why am I being mentioned here?

**Comment by GauravCreed** [comment]
Hi @janisozaur 

thanks for the quick response.

a little bit more research and experiment i got it.

Thanks Again. (_)
