### ISSUE TITLE
Get Bug || Failed to enter Join Multiplayer Game

### ISSUE THREAD

**Issue by fadligenta** [shlusiak/Freebloks-Android#18]
#### Expected behavior<br>
<br>
I hope when joining in multiplayer game does not happen a problem<br>
<br>
#### Actual behavior<br>
<br>
The fact is when I ask to join always can not and this is an obstacle for me.Please repair<br>
<br>
#### How to reproduce<br>
<br>
* Download the freebloks app on playstore Or [Here](https://play.google.com/store/apps/details?id=de.saschahlusiak.freebloks)
* Launch App<br>
* Touch to skip tutorial<br>
* Then comes the &quot;Host&quot; and &quot;Join&quot; button<br>
* Now please select Join button<br>
* Fill in your name and select the &quot;Internet&quot; button<br>
* Waiting for a moment to connect then the Notice appears failed
- Device used: Samsung Grand prime SM-G530<br>
<br>
* Operating System: Android version 4.4.4<br>
<br>
* Application version: 1.0.5

#### Recording Of The Bug
https://youtu.be/xY1AZfqwMds

this is a proof of my Internet connection work 

https://youtu.be/6hzKiG8RuFA

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@fadligenta/get-bug-or-or-failed-to-enter-join-multiplayer-game">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by shlusiak** [comment]
The whole app is getting a major refactoring and rewrite. Closing for now as not reproducable.
