### ISSUE TITLE
Build Exception

### ISSUE THREAD

**Issue by gspeiliu** [shlusiak/Freebloks-Android#19]
I tried to build APK on my self. However, the error gdb.mk:33: *** missing separator.  Stop. happened.

I tried to execute the following build command one by one.
git submodule init
git submodule update
./gradlew assembleDebug

Crash info:
> Task :generateJsonModelStandardAmazonDebug FAILED
/xxx/Sdk/ndk/20.0.5594570/build/core/gdb.mk:33: *** missing separator.  Stop.

Thanks

**Comment by shlusiak** [comment]
Hi @gspeiliu,

I see you have the ndk version `20.0.559470` installed. Would you mind trying if this works with the latest version of the ndk? I have version `21.2.6472646` installed and it is working without a problem for me.

Is there any more of the output above the error that might indicate the root of the problem?

Cheers,
Sascha

**Comment by gspeiliu** [comment]
Hi @shlusiak 

I tried to use the version 21.2.6472646, the error message as follow:
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'Freebloks-Android'.
> No version of NDK matched the requested version 20.0.5594570. Versions available locally: 21.2.6472646, 21.2.6472646

I do not know why does the project request version 20.0.5594570. Actually the previous running under all of the NDK available which installed by using Android Studio SDK manager.

Thanks

**Comment by shlusiak** [comment]
The project does not request a specific version of the ndk, I'm unsure where that value comes from. Have you tried loading the project in Android Studio and compiling it from there? Sometimes it does additional configuration of the project for the current environment.

**Comment by gspeiliu** [comment]
Hi I tried with Android Studio on Ubuntu 18.04 LTS. The error message is still there. The while error info as follow:
* What went wrong:
Execution failed for task ':app:generateJsonModelDevDebug'.
> Build command failed.
  Error while executing process /mnt/xxxxxx/Downloads/Android/ndk/20.0.5594570/ndk-build with arg
uments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=/home/peiliu/Downloads/BuildSystem/Repos/nikita36078#J2ME-Lo
ader/app/src/main/cpp/Android.mk APP_ABI=armeabi-v7a NDK_ALL_ABIS=armeabi-v7a NDK_DEBUG=1 APP_PLATFORM=andr
oid-16 NDK_OUT=/home/peiliu/Downloads/BuildSystem/Repos/nikita36078#J2ME-Loader/app/build/intermediates/ndkBuild/devDebug/obj NDK_LIBS_OUT=/home/peiliu/Downloads/BuildSystem/Repos/nikita36078#J2ME-Loader/app/build/
intermediates/ndkBuild/devDebug/lib APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}

  /mnt/xxxxxx/Downloads/Android/ndk/20.0.5594570/build/core/gdb.mk:33: *** missing separator.  Stop.

ls /xxx/Android/ndk
18.1.5063045  20.0.5594570  21.2.6472646

**Comment by shlusiak** [comment]
@gspeiliu just a guess, but does your repository directory have a # symbol in the path (`nikita36078#J2ME-Loader`)? Maybe the script is breaking somehow because of that?

**Comment by gspeiliu** [comment]
Actually, I tried to build under different OS. Mac OS 10.15 can build successfully via the same directory, which is the clone directory.

**Comment by gspeiliu** [comment]
Thanks for your help. It is the repo directory symbol #  that makes the error happen. :-)
