### ISSUE TITLE
submodule points to unknown commit

### ISSUE THREAD

**Issue by jspricke** [shlusiak/Freebloks-Android#22]
Can you please fix the git submodule reference? This broke in: https://github.com/shlusiak/Freebloks-Android/commit/259d7c7095c956f1c69995db96e63fc88eb0af58#diff-4fd604094858f98b3705f69ecf8c6f047768b8988339518174e9f8dae1ab7983
I guess you are missing a push in Freebloks-3D.

Thanks!

(This showed up in the F-Droid logs)

**Comment by shlusiak** [comment]
Ooh thanks! Yup, missed to push the submodule, done that now, hope that works. Thanks for notifying me.
