### ISSUE TITLE
Allow the possibility to review the game

### ISSUE THREAD

**Issue by guy-teube** [shlusiak/Freebloks-Android#24]
Hello,
Actually when the game is finished, the application displays the table of the score. The game board is in background, but it's not possible to see it again.
[screnshot](https://postimg.cc/ftMKVYBV)
Can you provide the possibility to hide the scores, to see the game board again? It should allow a screenshot if we make a new highest score, or simply discuss the game, as we do after an offline game.
Thank you

(note: as you can see in the screenshot, the remaining parts are not so readable in a small smartphone - mine is 5.0 inch)

**Comment by shlusiak** [comment]
That is a great suggestion! I will keep that in mind and think of a good solution for this problem for the next update. :) I'm not having as much time to work on this as I wish, but this will not be forgotten.

**Comment by shlusiak** [comment]
The latest update adds a close button to the finish dialog, which allows you to view the game again after it was finished, to review and to take screenshots. :) I know it's very subtly though.
